# TENSORS
* A torch tensor is a multi-dimensional matrix containing elements of a single datatype.
* Similar to Numpy Arrays, but full of fun things that make them work better on GPUs (vs regular CPUs).
* Default data type of float32.
* More suitable for deep learning than a numpy array.

In [1]:
import torch
import numpy as np

# LISTS

In [2]:
my_list = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# NUMPY ARRAYS

In [3]:
np1 = np.random.rand(3, 4)
np1

array([[0.21930259, 0.3002728 , 0.91484906, 0.10622019],
       [0.87560449, 0.40509671, 0.02999229, 0.60270997],
       [0.18177383, 0.12722074, 0.32528003, 0.21970883]])

In [4]:
np1.dtype

dtype('float64')

# TENSORS

In [5]:
tensor_2d = torch.randn(3, 4)
tensor_2d
#tensor_2d.dtype

tensor([[ 1.8862, -2.9783,  0.6703,  1.4635],
        [-1.3734, -0.8637, -0.4212, -1.0311],
        [-0.4767, -0.6246, -0.9942,  0.7304]])

In [6]:
tensor_3d = torch.zeros(2, 3, 4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.2193, 0.3003, 0.9148, 0.1062],
        [0.8756, 0.4051, 0.0300, 0.6027],
        [0.1818, 0.1272, 0.3253, 0.2197]], dtype=torch.float64)