# TENSOR MATH OPERATIONS
* Add, Subtract, Multiply, Divide, Remainders, Exponents
* Shorthand and uh, Longhand
* Reassignment

In [23]:
import torch
import numpy as np

In [24]:
tensor_a = torch.tensor([1, 2, 3, 4])
tensor_b = torch.tensor([5, 6, 7, 8])

In [25]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [26]:
# Addition longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [27]:
# Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [28]:
# Subtraction function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [29]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [30]:
# Multiplication function
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [31]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [32]:
# Division function
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [33]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [34]:
# Remainder longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [35]:
# Exponents / power
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [36]:
# Exponents / power longhand
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [37]:
# Another way to write longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [38]:
# Reassignment
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [39]:
tensor_a

tensor([1, 2, 3, 4])

In [40]:
# Could do tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [41]:
# Note that usinng the underscore after the add function performed reassignment on tensor_a
tensor_a

tensor([ 6,  8, 10, 12])